
PUT  http://localhost:3000/api/blogs/5beab42e7aaef9c502c16b3f
Content-Type: application/json

{
  "title": "Roth and Kona sub-10",
  "author": "Pauli Kiurux",
  "url": "http://triathlonhaaste.blogspot.com/",
  "likes": 1
}